### PR TITLE
Compile speedups for better performance

### PR DESCRIPTION
**Pull request by jjhelmus**
Enable compiled _speedups module for better performance.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
Was just about to do the same, thanks @ocefpaf

**Comment by ocefpaf** [comment]
> Was just about to do the same, thanks @ocefpaf

Sorry for stepping on your toes :grimacing: I guess that I'm reacting too much on every GH notification lately. I'll stop it for today :smile:

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
Re-rendering picked up the new compiler syntax.   This should be good to go now @ocefpaf.

**Pull request merged**
